language: node_js
node_js:
  - '12'
before_install:
  - 'git config --global "user.name" "$GIT_USERNAME"'
  - 'git config --global "user.email" "$GIT_EMAIL"'
  - 'echo $NPMRC >> ~/.npmrc'
  - 'echo "progress=false" >> ~/.npmrc'
install:
  - 'npm install'
script:
  - 'node ./run.js'

