pkgs:
  - name: offensive
    repoUrl: git@github.com:mchalapuk/offensive.js.git
    pwdVar: OFFENSIVE_PWD
    testTask: all
    deployTask: deploy
  - name: fake-promise
    repoUrl: git@github.com:mchalapuk/fake-promise.git
    pwdVar: FAKE_PROMISE_PWD
    testTask: clean-build
    deployTask: deploy
  - name: webpack-external-react
    repoUrl: git@github.com:mchalapuk/webpack-external-react.git
    pwdVar: WEBPACK_EXTERNAL_REACT_PWD
    testTask: test
    deployTask: deploy
  - name: aono
    repoUrl: git@github.com:aono-logger/aono.git
    pwdVar: AONO_PWD
    testTask: clean-build
    deployTask: deploy
  - name: wson-dom-connector
    repoUrl: git@github.com:mchalapuk/wson-dom-connector.git
    pwdVar: DOM_CONNECTOR_PWD
    testTask: test
    deployTask: deploy
  - name: wson-event-connector
    repoUrl: git@github.com:mchalapuk/wson-event-connector.git
    pwdVar: EVENT_CONNECTOR_PWD
    testTask: test
    deployTask: deploy
  - name: gulp-query-selector
    repoUrl: git@github.com:mchalapuk/gulp-query-selector.git
    pwdVar: GULP_QUERY_SELECTOR_PWD
    testTask: test
    deployTask: deploy
