pkgs:
  - name: offensive.js
    repoUrl: git@github.com:mchalapuk/offensive.js.git
    pwdVar: OFFENSIVE_PWD
    testTask: all
    deployTask: deploy
  - name: wson-event-connector
    repoUrl: git@github.com:mchalapuk/wson-event-connector.git
    pwdVar: EVENT_CONNECTOR_PWD
    testTask: test
    deployTask: deploy
